profiles:
  active: dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Tributo2019*GTS
    url: jdbc:mysql://tributoaws.cflyqudqcoq8.us-east-2.rds.amazonaws.com:3306/tributo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jackson:
    locale: es_CO
    time-zone: America/Bogota
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    database: MYSQL
    openInView: false
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
    port : 5000
